# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TtroCurrencyCalculatorSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TtroCurrencyCalculatorSample
  pod 'PayWandModelProtocols', :path => '../../PayWandModelProtocols/'
  pod 'PayWandBasicElements', :path => '../../PayWandBasicElements/'
  pod 'TtroPopView', :path => '../../TtroPopView'
  pod 'TtroCountryPicker', :path => '../../TtroCountryPicker/'
  pod 'TtroCurrencyCalculator', :path => '../'

end
